spring:
  application:
    name: GraphQLProxy

server:
  port: 4000

resilience4j:
  retry:
    instances:
      healthCheck:
        maxAttempts: 10
        waitDuration: 100ms
  circuitbreaker:
    instances:
      healthCheck:
        slidingWindowSize: 50
        failureRateThreshold: 80
  ratelimiter:
    instances:
      healthCheck:
        limitForPeriod: 1000
        timeoutDuration: 1s
  bulkhead:
    instances:
      healthCheck:
        maxConcurrentCalls: 500
        maxWaitDuration: 500ms

targetUrl:
  monolithicService: ${MONOLITHIC_SERVICE_URL:http://localhost:8080/graphql}